import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import React from "react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  applicationName: "My App",
  viewport:"width=device-width, initial-scale=1, viewport-fit=cover",

  icons: [
    {
      url: "/icons/icon-192.png",
      sizes: "192x192",
      type: "image/png"
    },
    {
      url: "/icons/icon-512.png",
      sizes: "512x512",
      type: "image/png"
    },
    {
      url: "/icons/apple-touch-icon.png",
      sizes: "180x180",
      rel: "apple-touch-icon",
    },
    {
      url: "/icons/apple-touch-icon.png",
      sizes: "180x180",
      rel: "apple-touch-icon-precomposed",
    },
  ]
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
