import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import React from "react";
import Head from "next/head";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  applicationName: "My App",
  viewport:"width=device-width, initial-scale=1, viewport-fit=cover",

  icons: [
    {
      url: "/icons/icon-192.png",
      sizes: "192x192",
      type: "image/png"
    },
    {
      url: "/icons/icon-512.png",
      sizes: "512x512",
      type: "image/png"
    },
    {
      url: "/icons/apple-touch-icon.png",
      sizes: "180x180",
      rel: "apple-touch-icon",
    },
    {
      url: "/icons/apple-touch-icon.png",
      sizes: "180x180",
      rel: "apple-touch-icon-precomposed",
    },
  ]
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
  <title>My App</title>
  <meta name="apple-mobile-web-app-capable" content="yes" />

  <meta name="viewport" content="width=device-width, initial-scale=1, minimal-ui, viewport-fit=cover" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
  <meta name="apple-mobile-web-app-title" content="My App" />
  <meta name="apple-touch-fullscreen" content="yes" />
  <link rel="manifest" href="/manifest.json" />
  <link rel="apple-touch-icon" href="/icons/apple-touch-icon.png" />
</Head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-[110vh]`}
      >
        {children}
      </body>
    </html>
  );
}
